### ISSUE TITLE
Lisensi?

### ISSUE THREAD

**Issue by aswansyahputra** [seuriously/caleg_dpr_2019#1]
Selamat siang,

Kerja yang sangat menarik, mas! Apakah ada syarat atau ketentuan untuk menggunakan hasil kerja ini?
Saya berencana memasukan hasil kerja mas ini sebagai dataset di package [`nusandata`](https://github.com/aswansyahputra/nusandata) apabila mas memberikan izin.

Salam,

Aswan

**Comment by seuriously** [comment]
Silahkan mas.

**Comment by aswansyahputra** [comment]
Baik, terimakasih mas.
